### ISSUE TITLE
fail to test

### ISSUE THREAD

**Issue by pgmot** [bitterfox/slack-java-api#71]

**Comment by pgmot** [comment]
そもそもテストをするときにサーバ叩きに行くのあまり行儀が良くない．
モックを作ってJSON食わした時にちゃんと動くかという手をテストすべき

**Comment by bitterfox** [comment]
そのあたりよくわからないので，いい感じにしてもらいたいです．

**Comment by bitterfox** [comment]
ちなみに，例外周りはサーバの実装に合わせたいので，リクエスト送ってるんですが，それもあんまり良くないですか？

**Comment by pgmot** [comment]
毎回サーバ叩くの良くないからそのJSONと合致してるかみたいな挙動チェックするほうがええで

**Comment by bitterfox** [comment]
そのJSONというと・・・？

**Comment by pgmot** [comment]
実際に取ってきておく

**Comment by bitterfox** [comment]
なるほど．

**Comment by pgmot** [comment]
実装としては，テスト用のApiとGetApiRequestを作って差し替えて，いい感じのApiResultを返すようにしたら内部実装変えなくていいと思う

**Comment by bitterfox** [comment]
わりかし大きなリファクタリングが必要そうなので，明日以降順次変えていきます．

とりま，実装は思いつきました．

**Comment by bitterfox** [comment]
ちなみに，そうした場合，実際に通信してデータとれてこれているか確認できないですがいいんです？

**Comment by pgmot** [comment]
ここでテストすべきなのは，あくまでもレスポンスに対して正しい挙動を行うことをテストすべきなのであって，
サーバと通信してデータを取れてこれているかというのは今テストすべきではない．
サーバと通信してテストするのは一つのテストでいいと思う．

自社開発とかでテストサーバ用意できるならサーバ叩くけど，slackのサーバ叩きまくるのはかなり行儀が悪いし気軽にテストできない．

**Comment by pgmot** [comment]
モック．この辺りのライブラリ使うと簡単だと思います．
http://qiita.com/mstssk/items/98e597c13f12746c907d

あと流れる話し合いはgitter使いましょう
