### ISSUE TITLE
gradleにしませんか

### ISSUE THREAD

**Issue by pgmot** [bitterfox/slack-java-api#72]
しませんか？

**Comment by bitterfox** [comment]
現状ではMavenで困っていないのと，Gradle2.x+NetBeansの組み合わせが未知数なので，冒険しなくてもいいと思います．
MavenだとNetBeansが標準でサポートしているのでその点での安心感は高いです．(といっても手元のNetBeansのMavenのバージョンが引くてテストを実行できなかったりしたんですけどね)

**Comment by pgmot** [comment]
NetBeans．．．うわあああああ．

はいお好きにPullReqもdeclineしていただいて結構ですよ．
gitignore PullReqはNetBeansを追加するのでちょっと待って下さい

**Comment by bitterfox** [comment]
あー，すいません．gitignoreマージしちゃいました．

**Comment by pgmot** [comment]
はい．そちらのタイミングで追加しておいてください．

**Comment by bitterfox** [comment]
ちなみに，Gradleにしたほうがいい理由とかありますか？

**Comment by pgmot** [comment]
柔軟な処理がかけます．
